import { eq } from "drizzle-orm";
import { getReadyDb } from "@/db";
import { projects } from "@/db/schema";
import { isAdminRequest } from "@/lib/admin-auth";
import { projectSchema } from "@/lib/validation";
type Context={params:Promise<{id:string}>};
function normalize(data:Record<string,unknown>){const result={...data};if("gallery" in result)result.gallery=JSON.stringify(result.gallery||[]);if("technologies" in result)result.technologies=JSON.stringify(result.technologies||[]);if(result.coverImage==="")result.coverImage=null;if(result.projectUrl==="")result.projectUrl=null;if(result.githubUrl==="")result.githubUrl=null;return result;}
export async function PUT(request:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;const parsed=projectSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message||"Dados inválidos"},{status:400});try{const [project]=await (await getReadyDb()).update(projects).set({...normalize(parsed.data),updatedAt:new Date().toISOString()} as typeof projects.$inferInsert).where(eq(projects.id,Number(id))).returning();if(!project)return Response.json({error:"Projeto não encontrado"},{status:404});return Response.json({project});}catch{return Response.json({error:"Não foi possível salvar as alterações."},{status:500});}}
export async function PATCH(request:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;const parsed=projectSchema.partial().safeParse(await request.json());if(!parsed.success)return Response.json({error:"Alteração inválida"},{status:400});const [project]=await (await getReadyDb()).update(projects).set({...normalize(parsed.data),updatedAt:new Date().toISOString()} as typeof projects.$inferInsert).where(eq(projects.id,Number(id))).returning();return Response.json({project});}
export async function DELETE(_:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;await (await getReadyDb()).delete(projects).where(eq(projects.id,Number(id)));return Response.json({ok:true});}
