import { eq } from "drizzle-orm";
import { getReadyDb } from "@/db";
import { projects } from "@/db/schema";
import { isAdminRequest } from "@/lib/admin-auth";
import { projectSchema } from "@/lib/validation";
import { isBlobStoreConfigured, mutatePortfolioState } from "@/lib/blob-store";
type Context={params:Promise<{id:string}>};
function normalize(data:Record<string,unknown>){const result={...data};if("gallery" in result)result.gallery=JSON.stringify(result.gallery||[]);if("technologies" in result)result.technologies=JSON.stringify(result.technologies||[]);if(result.coverImage==="")result.coverImage=null;if(result.projectUrl==="")result.projectUrl=null;if(result.githubUrl==="")result.githubUrl=null;return result;}
export async function PUT(request:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;const numericId=Number(id);const parsed=projectSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message||"Dados inválidos"},{status:400});try{if(isBlobStoreConfigured()){const project=await mutatePortfolioState((state)=>{const index=state.projects.findIndex(item=>item.id===numericId);if(index<0)return null;if(state.projects.some(item=>item.id!==numericId&&item.slug===parsed.data.slug))throw new Error("DUPLICATE_SLUG");const previous=state.projects[index];const updated={...parsed.data,id:numericId,coverImage:parsed.data.coverImage||null,projectUrl:parsed.data.projectUrl||null,githubUrl:parsed.data.githubUrl||null,createdAt:previous.createdAt,updatedAt:new Date().toISOString()};state.projects[index]=updated;return updated;});if(!project)return Response.json({error:"Projeto não encontrado"},{status:404});return Response.json({project});}const [project]=await (await getReadyDb()).update(projects).set({...normalize(parsed.data),updatedAt:new Date().toISOString()} as typeof projects.$inferInsert).where(eq(projects.id,numericId)).returning();if(!project)return Response.json({error:"Projeto não encontrado"},{status:404});return Response.json({project});}catch(error){const message=error instanceof Error&&error.message.includes("DUPLICATE_SLUG")?"Este slug já está em uso.":"Não foi possível salvar as alterações.";return Response.json({error:message},{status:500});}}
export async function PATCH(request:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;const numericId=Number(id);const parsed=projectSchema.partial().safeParse(await request.json());if(!parsed.success)return Response.json({error:"Alteração inválida"},{status:400});if(isBlobStoreConfigured()){const project=await mutatePortfolioState((state)=>{const index=state.projects.findIndex(item=>item.id===numericId);if(index<0)return null;if(parsed.data.slug&&state.projects.some(item=>item.id!==numericId&&item.slug===parsed.data.slug))throw new Error("DUPLICATE_SLUG");const updated={...state.projects[index],...parsed.data,id:numericId,coverImage:parsed.data.coverImage===""?null:(parsed.data.coverImage??state.projects[index].coverImage),projectUrl:parsed.data.projectUrl===""?null:(parsed.data.projectUrl??state.projects[index].projectUrl),githubUrl:parsed.data.githubUrl===""?null:(parsed.data.githubUrl??state.projects[index].githubUrl),updatedAt:new Date().toISOString()};state.projects[index]=updated;return updated;});if(!project)return Response.json({error:"Projeto não encontrado"},{status:404});return Response.json({project});}const [project]=await (await getReadyDb()).update(projects).set({...normalize(parsed.data),updatedAt:new Date().toISOString()} as typeof projects.$inferInsert).where(eq(projects.id,numericId)).returning();return Response.json({project});}
export async function DELETE(_:Request,{params}:Context){if(!await isAdminRequest())return Response.json({error:"Não autorizado"},{status:401});const {id}=await params;const numericId=Number(id);if(isBlobStoreConfigured()){const removed=await mutatePortfolioState((state)=>{const originalLength=state.projects.length;state.projects=state.projects.filter(item=>item.id!==numericId);return state.projects.length!==originalLength;});if(!removed)return Response.json({error:"Projeto não encontrado"},{status:404});return Response.json({ok:true});}await (await getReadyDb()).delete(projects).where(eq(projects.id,numericId));return Response.json({ok:true});}
