ALTER TABLE `site_settings` ADD `avatar` text DEFAULT '' NOT NULL;
--> statement-breakpoint
UPDATE `site_settings` SET `avatar` = 'https://avatars.githubusercontent.com/u/117962301?v=4' WHERE `id` = 1 AND `avatar` = '';
--> statement-breakpoint
INSERT OR IGNORE INTO `projects` (`title`,`slug`,`short_description`,`description`,`technologies`,`category`,`project_date`,`project_url`,`github_url`,`challenge`,`solution`,`result`,`featured`,`published`) VALUES
('Sistema de Reembolsos','sistema-de-reembolsos','Plataforma full stack para solicitar, aprovar, pagar e exportar reembolsos de um evento acadêmico.','Aplicação completa com formulário público e painel administrativo para gerenciar solicitações, calcular valores individuais, registrar ações e preparar pagamentos via PIX.','["Next.js","TypeScript","Prisma","PostgreSQL","JWT"]','Aplicação Full Stack','2026',NULL,NULL,'Centralizar um processo de reembolso que precisava de controle por participante, cálculo automático e histórico confiável de cada decisão.','A solução combina Next.js, Prisma e PostgreSQL com autenticação administrativa, proteção CSRF, validação Zod, exportação para Excel e integração preparada para Mercado Pago.','Um fluxo completo para receber pedidos, aprovar ou rejeitar solicitações, controlar pagamentos e exportar relatórios sem depender de planilhas soltas.',1,1);
--> statement-breakpoint
INSERT OR IGNORE INTO `projects` (`title`,`slug`,`short_description`,`description`,`technologies`,`category`,`project_date`,`project_url`,`github_url`,`challenge`,`solution`,`result`,`featured`,`published`) VALUES
('TrantaPromos','trantapromos','Robô de promoções para Telegram com agendamento de tarefas, API própria e persistência de dados.','Automação em Python criada para organizar e distribuir ofertas permitidas em canais do Telegram, com processamento assíncrono e estrutura pronta para operação contínua.','["Python","FastAPI","SQLAlchemy","APScheduler","Telegram"]','Bot / Automação','2026',NULL,NULL,'Construir um robô de ofertas que pudesse trabalhar continuamente, separar responsabilidades e manter o histórico necessário para a automação.','O projeto usa FastAPI para a camada de serviço, APScheduler para rotinas programadas, HTTPX para integrações assíncronas e SQLAlchemy para persistência.','Uma base organizada e pronta para executar automações de promoções com implantação em container e expansão de novas fontes e canais.',1,1);
--> statement-breakpoint
INSERT OR IGNORE INTO `projects` (`title`,`slug`,`short_description`,`description`,`technologies`,`category`,`project_date`,`project_url`,`github_url`,`challenge`,`solution`,`result`,`featured`,`published`) VALUES
('Portal JP','portal-jp','Portal autenticado para envio, listagem, download e exclusão controlada de arquivos.','Aplicação web com login e área privada para organizar arquivos enviados pelos usuários, incluindo controle de sessão e operações protegidas no servidor.','["Node.js","Express","SQLite","Sessions","Multer"]','Portal Web','2025',NULL,NULL,'Criar uma área privada simples em que apenas usuários autenticados pudessem enviar e administrar arquivos.','Foi usado Express com sessões, bcrypt para autenticação, Multer para uploads e SQLite para registrar usuários e metadados dos arquivos.','Um protótipo funcional de portal privado com autenticação e ciclo completo de gerenciamento de arquivos.',0,1);
--> statement-breakpoint
PRAGMA optimize;
