export type Project = { id:number; title:string; slug:string; shortDescription:string; description:string; coverImage:string|null; gallery:string[]; technologies:string[]; category:string; projectDate:string; projectUrl:string|null; githubUrl:string|null; showProjectLink:boolean; challenge:string; solution:string; result:string; featured:boolean; published:boolean; createdAt?:string; updatedAt?:string; };
export type ContactMessage = { id:number; name:string; email:string; subject:string; message:string; status:"new"|"read"|"replied"; createdAt:string; };
export type SiteSettings = { id?:number; name:string; headline:string; bio:string; email:string; avatar:string; github:string; linkedin:string; instagram:string; whatsapp:string; };

export const defaultSettings: SiteSettings = { name:"Joao Pedro dos Santos", headline:"Programador Freelancer", bio:"Sou programador freelancer desde setembro de 2024. Crio scripts e mod menus em Lua para FiveM, bots para Discord, sites e aplicações, transformando ideias em soluções funcionais e feitas sob medida.", email:"contato.jpsouzasantos@gmail.com", avatar:"/joao-pedro.png", github:"https://github.com/guinafps", linkedin:"", instagram:"https://www.instagram.com/jpkku_/", whatsapp:"https://wa.me/5567992227140?text=Ol%C3%A1%2C%20vim%20do%20seu%20portif%C3%B3lio!" };

export const demoProjects: Project[] = [
  { id:3, title:"Sistema de Reembolsos", slug:"sistema-de-reembolsos", shortDescription:"Plataforma full stack para solicitar, aprovar, pagar e exportar reembolsos de um evento acadêmico.", description:"Aplicação completa com formulário público e painel administrativo para gerenciar solicitações, calcular valores individuais, registrar ações e preparar pagamentos via PIX.", coverImage:null, gallery:[], technologies:["Next.js","TypeScript","Prisma","PostgreSQL","JWT"], category:"Aplicação Full Stack", projectDate:"2026", projectUrl:null, githubUrl:null, showProjectLink:false, featured:true, published:true, challenge:"Centralizar um processo de reembolso que precisava de controle por participante, cálculo automático e histórico confiável de cada decisão.", solution:"A solução combina Next.js, Prisma e PostgreSQL com autenticação administrativa, proteção CSRF, validação Zod, exportação para Excel e integração preparada para Mercado Pago.", result:"Um fluxo completo para receber pedidos, aprovar ou rejeitar solicitações, controlar pagamentos e exportar relatórios sem depender de planilhas soltas." },
  { id:4, title:"TrantaPromos", slug:"trantapromos", shortDescription:"Robô de promoções para Telegram com agendamento de tarefas, API própria e persistência de dados.", description:"Automação em Python criada para organizar e distribuir ofertas permitidas em canais do Telegram, com processamento assíncrono e estrutura pronta para operação contínua.", coverImage:null, gallery:[], technologies:["Python","FastAPI","SQLAlchemy","APScheduler","Telegram"], category:"Bot / Automação", projectDate:"2026", projectUrl:null, githubUrl:null, showProjectLink:false, featured:true, published:true, challenge:"Construir um robô de ofertas que pudesse trabalhar continuamente, separar responsabilidades e manter o histórico necessário para a automação.", solution:"O projeto usa FastAPI para a camada de serviço, APScheduler para rotinas programadas, HTTPX para integrações assíncronas e SQLAlchemy para persistência.", result:"Uma base organizada e pronta para executar automações de promoções com implantação em container e expansão de novas fontes e canais." },
  { id:2, title:"Portal JP", slug:"portal-jp", shortDescription:"Portal autenticado para envio, listagem, download e exclusão controlada de arquivos.", description:"Aplicação web com login e área privada para organizar arquivos enviados pelos usuários, incluindo controle de sessão e operações protegidas no servidor.", coverImage:null, gallery:[], technologies:["Node.js","Express","SQLite","Sessions","Multer"], category:"Portal Web", projectDate:"2025", projectUrl:null, githubUrl:null, showProjectLink:false, featured:false, published:true, challenge:"Criar uma área privada simples em que apenas usuários autenticados pudessem enviar e administrar arquivos.", solution:"Foi usado Express com sessões, bcrypt para autenticação, Multer para uploads e SQLite para registrar usuários e metadados dos arquivos.", result:"Um protótipo funcional de portal privado com autenticação e ciclo completo de gerenciamento de arquivos." },
  { id:1, title:"Gerador Spotify", slug:"gerador-spotify", shortDescription:"Experimento em Node.js para gerar identificadores aleatórios e exportar os resultados em um arquivo de texto.", description:"Projeto de linha de comando que recebe a quantidade desejada, cria strings aleatórias com o módulo crypto do Node.js, monta URLs e salva a lista em um arquivo local.", coverImage:null, gallery:[], technologies:["Node.js","JavaScript","Crypto","File System"], category:"Automação / CLI", projectDate:"2024", projectUrl:null, githubUrl:"https://github.com/guinafps/geradorspotify", showProjectLink:false, featured:false, published:true, challenge:"Praticar a criação de uma ferramenta simples de terminal que valide entradas e gere vários resultados de forma automatizada.", solution:"O script usa crypto.randomInt para compor identificadores, readline para capturar a quantidade e fs para gravar a saída em um arquivo de texto.", result:"Um protótipo compacto que reúne entrada via terminal, geração aleatória e persistência local em um único fluxo." },
];

export function projectTone(project:Project){ const tones=["ember","cobalt","violet","acid"]; return tones[Math.abs(project.id)%tones.length]; }
export function safeJsonArray(value:unknown):string[]{ if(Array.isArray(value)) return value.filter((item):item is string=>typeof item==="string"); if(typeof value!=="string") return []; try{return safeJsonArray(JSON.parse(value));}catch{return value.split(",").map(item=>item.trim()).filter(Boolean);} }
